/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * SimInternalFrame.java
 *
 * Created on May 25, 2009, 10:18:13 AM
 */

package applications;

import simulation.Simulation;

/**
 *
 * @author ae3263
 */
public class SimInternalFrame extends javax.swing.JInternalFrame {

    /** Creates new form SimInternalFrame */
    public SimInternalFrame() {
        super("",true,true,true,true);
        initComponents();
        setVisible(true);
    }

    SimInternalFrame(String name) {
        this();
        setTitle(name);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        simPanel1 = new applications.SimPanel();

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(simPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 792, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(simPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 458, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public applications.SimPanel simPanel1;
    // End of variables declaration//GEN-END:variables

}
